
version: 2

models:
  - name: fast_vehicle_model
    description: "Query fast vehicles"
    
  - name: vehicle_summary_model
    description: "A summary of vehicles by distance and speed"
  
  - name: fast_vehicle_summary_model
    description: "A summary of vehicles by distance and speed"

  - name: timely_summary_model
    description: "A summary of vehicles by speed"

  - name: speed_timely_summary_model
    description: "A summary of vehicles by distance and speed"

  - name: lat_timely_summary_model
    description: "A summary of vehicles by distance and speed"

  - name: lon_timely_summary_model
    description: "A summary of vehicles by distance and speed"

